atorus-research/xportr

- README.Rmd
- README.md
I took out those articles that Ross was trying to find
Can you see if the cli checks and x's render appropriately?  Mine don't seem to be displaying correctly.  
But they do in the rmarkdown chunks:
> Removed reference to articles

- .github/workflows/check-standard.yaml
- DESCRIPTION
- NEWS.md
- R/utils-xportr.R
- man/xportr-package.Rd
- tests/testthat/test-write.R
Per #60 and #64 , users seem to encounter this error with relative frequency: 
"Error: Writing failure: A provided format string could not be understood."  
I believe this is actually a `haven` error-message coming from line 55 in `R/write.R` :  
`write_xpt(data, path = path, version = 5, name = name)`
To remedy this, I propose to add an additional format check inside `xpt_validate()` which is called at line 47 of `R/write.R`, but changes are contained inside `R/utils-xportr.R`
> More helpful error message for invalid formats

- R/utils-xportr.R
- R/zzz.R
Per #69 , add user's requested time formats
> Closes #69 add time formats

- NEWS.md
- R/format.R
- tests/testthat/test-metadata.R
This closes #69.
Idea here is to remove any null or NA formats and convert them to "". This is due to a limitation in haven that will break any NA 'sas.formats'
> Add logic to convert any null or NA formats to "" for haven.

- NEWS.md
- R/type.R
- tests/testthat/test-type.R
Fixes #75
The issue here was that coercing columns with `as.character()` or `as.numeric()` strips all attributes, not just the class attribute that we want to be rid of. I made a change to save attributes besides class (such as width, label, and format.sas), then restore those classes after coercion. I also wrote a test that checks for identical results whether `xportr_type()` is called at the beginning or end of a pipeline.
The function `metacore::set_variable_labels()` was also referenced in the original issue. I cannot find such a function in metacore, so I have not tested against it here. If it sets labels with an attribute like xportr does, this will fix it as well.
Should I ask the original issue filer to install this version for testing?
Please let me know if there's anything you …
> Don't overwrite label, width, or sas.format in `xportr_type()`

- tests/testthat/test-metadata.R
- tests/testthat/test-pkg-load.R
- tests/testthat/test-type.R
- tests/testthat/test-utils-xportr.R
- tests/testthat/test-write.R
- #82 
1. Adds tests for `.onLoad()` function that sets the default options when the package is loaded
2. Increase the coverage for `xportr_df_label()` by piping second time - So we also test the case when the `_xportr.df_arg_` is already set.
3. Increase the coverage for `xportr_type()` by covering two cases:
- When the passed domain is not a character
- When metadata is a metacore object
4. Add a few trivial tests to cover the `utils-xportr.R`
5. Rewrite to cover all the cases handled by the `xportr_write()`
> Closes #82: Increase Test Coverage to 100%

- _pkgdown.yml
Closes:
- #109 
1. Adds the test-related internal functions as `internal` so that pkgdown ignores them.
> Closes #109 Fix the error of unable to build the pkgdown site

- NEWS.md
- R/format.R
- R/label.R
- R/length.R
- R/order.R
- R/type.R
- tests/testthat/test-order.R
We have developed a Pull Request template to aid you and our reviewers.  Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the xportr codebase remains robust and consistent.  
`{xportr}`'s scope is to enable R users to write out submission compliant `xpt` files that can be delivered to a Health Authority or to downstream validation software programs.  We see labels, lengths, types, ordering and formats from a dataset specification object (SDTM and ADaM) as being our primary focus. We also see messaging and warnings to users around applying information from the specification file as a primary focus. Please make sure your Pull Request meets this **scope of {xportr}**. If your Pull Request moves beyond this scope, please get …
> #149 - metadata order column to numeric

- vignettes/deepdive.Rmd
- vignettes/xportr.Rmd
Instead of making a bunch of loose suggestions, consider this PR against #141 
* font-weight to `500` instead of bold (middle ground between normal and bold)
* line-height so that there's no overlap in letters
* font-size changed to match `code` size
* removes rownames from datatables on `xportr` vignette
* Corrects spelling error
* Corrects styler error
> Suggestions on PR #141

- R/write.R
- _pkgdown.yml
- man/xportr_write.Rd
We have developed a Pull Request template to aid you and our reviewers.  Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the xportr codebase remains robust and consistent.  
`{xportr}`'s scope is to enable R users to write out submission compliant `xpt` files that can be delivered to a Health Authority or to downstream validation software programs.  We see labels, lengths, types, ordering and formats from a dataset specification object (SDTM and ADaM) as being our primary focus. We also see messaging and warnings to users around applying information from the specification file as a primary focus. Please make sure your Pull Request meets this **scope of {xportr}**. If your Pull Request moves beyond this scope, please get …
> #docs: example and ref blurb

- NEWS.md
- README.Rmd
- _pkgdown.yml
- man/xportr_write.Rd
- vignettes/deepdive.Rmd
- vignettes/xportr.Rmd
Changes:
- Remove the argument verbose from the xportr_format() function calls in examples
- Removes the warning when trying to build the pkgdown site by having consistent VignetteIndexEntry name for “Getting Started”
- Minor format changes to the NEWS.md
- Lint the _pkgdown configuration
> docs: make some minor document related changes

- tests/testthat/test-type.R
@bms63 this will correct the lint problems
* Corrects lintr errors that appear with new version of the package `lintr 3.1.0`
> Fix lint errors in `devel` that appear with new version of `{lintr}` 📦

- NEWS.md
- R/type.R
Adds a single line to `xportr_type()` that makes it drop the `levels` attribute of a factor column when the type is changed
Closes #159
> Make `xportr_type()` drop factor levels

- NEWS.md
- R/df_label.R
- R/format.R
- R/label.R
- R/length.R
- R/order.R
- R/type.R
- tests/testthat/test-depreciation.R
- tests/testthat/test-length.R
- tests/testthat/test-metadata.R
- tests/testthat/test-order.R
The use of `metacore` argument will now throw an error instead of a warning message.
> Hard deprecate the `metacore` argument

- R/write.R
- man/xportr_write.Rd
> Closes #226 - `metadata` is no longer inferred on `xportr_write`

- R/length.R
Closes #247 
The warning from the issue indicates we should start using the [selection helpers](https://tidyselect.r-lib.org/reference/all_of.html) to select from a variable. So this adds the `all_of()` to eliminate the warning.
> Use selection helpers during variable based selection

- NEWS.md
- vignettes/deepdive.Rmd
> Closes #215, #222: add `xportr()` and more details about length to deepdive

- R/split.R
- R/xportr-package.R
- R/xportr.R
- man/metadata.Rd
- man/xportr.Rd
- man/xportr_df_label.Rd
- man/xportr_format.Rd
- man/xportr_label.Rd
- man/xportr_length.Rd
- man/xportr_order.Rd
- man/xportr_split.Rd
- man/xportr_type.Rd
- man/xportr_write.Rd
> Doc updates per #261

- NEWS.md
Just a quick clean up of the news.  
* A few items were duplicated (bad merge??)
* Added issue numbers to entries missing issue numbers.
* Separated out Bug Fixes
@elimillera @EeethB - after this merge we can ship to CRAN.
> docs: clean up news for the release

- R/type.R
- tests/testthat/test-type.R
> Closes #275

- NEWS.md
- R/format.R
- R/label.R
- R/length.R
- R/messages.R
- R/order.R
- R/type.R
- tests/testthat/test-messages.R
- tests/testthat/test-type.R
Per #260, add logging when a domain is passed that isn't found in the metadata
Closes #260 
`{xportr}`'s scope is to enable R users to write out submission compliant `xpt` files that can be delivered to a Health Authority or to downstream validation software programs. We see labels, lengths, types, ordering and formats from a dataset specification object (SDTM and ADaM) as being our primary focus. We also see messaging and warnings to users around applying information from the specification file as a primary focus. Please make sure your Pull Request …
> Add missing domain logging

- tests/testthat/test-length.R
- tests/testthat/test-order.R
> Closes #290 Fix failing tests that are caused by metacore update (v.0.2.0)
